x
MadraySha2/java-explore-with-me pull request #4
Opened 2023-07-19 18:11 UTC by MadraySha2

2023-07-20 00:15 UTC, MadraySha2 commented
Добавлена основная функциональность сервиса. Настроена связка с сервисом статистики

2023-07-20 11:51 UTC, TomattmanYandex requested changes
Привет, комменты в коде + ниже
1. можно разбить контроллеры на подпакеты, по типу (админские публичные приватные)(но не обязательно)
2. в контроллеры можно было бы добавить логи

2023-07-20 11:51 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/AdminCatController.java
> +public class AdminCatController {
буквы недорогие, не надо их экономить

2023-07-20 11:51 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mapper/CompilationMapper.java
> +                .events(compilation.getEvents().stream()
так за маппинг ивентов будет отвечать только ивент маппер

2023-07-20 11:51 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/model/Sort.java
> +public enum Sort {
может это относится к дто а не к моделям

2023-07-20 12:40 UTC, MadraySha2 commented on main-service/src/main/java/ru/practicum/repository/EventRepository.java
> +    List<Event> findAllByInitiator_id(Long userId, Pageable pageable);
Привет!
Это разделители для Гибернэйта, по другому ругается :(

2023-07-21 09:16 UTC, TomattmanYandex requested changes
Привет, есть еще моменты которые стоит глянуть
1) Проверка на Null в маппера
2) пустой енам который не используется, оставь хотя бы комент если он зачем то нужен если нет, с глаз долой
3) првоерь методы репозитория с разделением буквой в верхнем регистре должно работать без нижних подчеркиваний
3) структуру базы данных руками создаем в schema файле

2023-07-21 09:16 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/mapper/EventMapper.java
> +        return events.stream().map(EventMapper::toEventShortDto).collect(Collectors.toList());
я бы проверить списсок перед обработкой, вдруг там null тогда будет очень неприятно

2023-07-21 09:16 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/repository/EventRepository.java
> +    List<Event> findAllByInitiator_id(Long userId, Pageable pageable);
а если findAllByInitiatorId
обычно он позволяет это, просто каждое подполе с большой буквы

2023-07-21 09:16 UTC, TomattmanYandex commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS compilation_events(
обычно так не делают, особенно в реальных проектах
в реальных проектах так вообще есть тулы для версионирования, 
вот представь сейчас ты запускаешь проект где то работать, и там накидываются данные, а потом у тебя новый таск,  и тебе надо будет добавить поле в таблицу, с текущей реализацией у тебя все похерится, но пересоздастся, со скриптом можно сделать так чтобы не похерилось

Но вообще в этих работах надо писать скрипты, так что давай, дерзай)))

маленький секрет, можно зайти в базу и выгрузить оттуда скрипты что создают точно такую же структуру)

2023-07-21 12:41 UTC, MadraySha2 commented
Штош... вроде все поправил
Этот пустой енам из-за ребэйса появлялся всегда, блин, у меня небольшая неразбериха с версиями была, откуда-то подхватился видимо

2023-07-22 08:48 UTC, TomattmanYandex approved these changes
Принято

2023-07-22 09:08 UTC, merged