Добавлена функция комментирования с возможность ставить лайки на комм…
MadraySha2/java-explore-with-me pull request #5
Opened 2023-07-25 10:12 UTC by MadraySha2

…енты, от чего меняется "полезность" коммента

2023-07-26 08:48 UTC, TomattmanYandex requested changes
Привет, очень невнятная логика по лакам дизлайкам особенно на уровне сервиса,
мне кажется что логика при наличии лайков и дизлайков должна быть однозначная  нажал лайк, он добавился, нажал повторно удалился) но если хочешь так оставить, то стоит немного переформатировать сервис
сделать два приватных метода, createLile (userID, eventId, isLike) и reverseLike(likeId)
вместо id там уже могут быть полноценные обьекты, так как это урвонеь сервиса и методы приватным, а дальше публичный метод, ищет лайк, если он есть то в любом случае происходит реверс  (проверь, кажется будет работаь при любой комбинации) а если нету, то происходит создание лфка или дизлайка)

2023-07-26 08:48 UTC, TomattmanYandex commented on README.md
стоит больше расписать о том то делает прокект, добавить больше информации от нем,

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/admin/AdminCommentController.java
> +        service.deleteComment(null, commentId, true);
что значит первый и последний параметр?

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/priv/PrivateCommentController.java
> +        service.deleteComment(userId, commentId, false);
что за третий параметр?

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/priv/PrivateCommentController.java
> +    public CommentDto getCommentById(@PathVariable Long userId, @PathVariable Long commentId) {
почти такой де метод есть в админском контроллере, так как пользователи скорее всего могут видеть все комменты к любому ивенту, то может стоит сделать этот коммент публичным

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/pub/PublicCommentController.java
> +    public List<CommentDto> getCommentsByEventInitiator(@PathVariable Long userId,
этот эндпоинт кажется относится к приватным

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +    public void deleteComment(Long userId, Long commentId, Boolean isAdmin) {
я бы сделал этот метод немного по другому
сделал бы методы deleteByOwner(userid, commentId) и deleteByAdmin(commentId)в первом бы делал проверки, во втором нет, так как уже ясно что это делается админом

2023-07-26 08:48 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +    public CommentDto likeComment(Long userId, Long commentId) { //мб будет не так понятно,но здесь при наличии лайка, он снимается при повторном нажатии
хорошо что есть коммент, потому что тяжело легко назвать метод так чтобы это было понятно, единственное лучше сделать его в фомате javaDoc

2023-07-26 11:58 UTC, MadraySha2 commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +        if (comment.getSender().getId().longValue() == userId.longValue()) {
Привет! В общем, сейчас разобрался, по сути, я так и хотел сделать, чтобы лайк снимался при повторном нажатии, и в лайке так и сделал, а в дизлайке, видимо отвлекся и сделал не так

2023-07-26 12:19 UTC, MadraySha2 commented on main-service/src/main/java/ru/practicum/controller/pub/PublicCommentController.java
> +    public List<CommentDto> getCommentsByEventInitiator(@PathVariable Long userId,
Привет!
Не совсем согласен, т.к. userId, мы передаем не свой id, а userId пользователя, на чьей странице мы находимся. Например, кто-то зашел на мою страницу и хочет увидеть, в целом комменты по моим событиям

2023-07-27 08:11 UTC, TomattmanYandex commented on README.md
> +<h1>Бэкэнд web-приложения для созадния и просмотра событий или подборок событий.</h1>
Все хорошо, но почему то, в файле другой ридми файл, значит скорее всего ты что то не так сгенерировал или отправил не то

2023-07-27 08:11 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/pub/PublicCommentController.java
> +    public List<CommentDto> getCommentsByEventInitiator(@PathVariable Long userId,
согласен, логично

2023-07-27 08:17 UTC, TomattmanYandex requested changes
Привет, еще есть ара доработок

2023-07-27 08:17 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +    public void deleteCommentAdmin(Long commentId) {
лучше поименовать deleteCommentByAdmin указываем, кем мы его удаляем

2023-07-27 08:17 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +    /* мб будет не так понятно,но здесь при наличии лайка, он снимается при повторном нажатии,
javaDoc это коменнт не для меня, а в целом к методу, так что стоит использовать его в другой форме, как описывающий функциональность метода

2023-07-27 08:17 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +    private final CommentRepository repository;
что за именование переменных все переменные это репоизитории а только один из них назван как репозиторий, а остальные вообще по имени не понять что за они 
переименовать

2023-07-27 08:17 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/CommentService.java
> +        /*Соотв. тут он проверяет, если это лайк, то он его убирает*/
логика теперь понятна, но комментарии немного переписать, основного вообще хватит, но если очень хочется то лучше следующий переделать, чтобы он не был вот так вот в середине строки кода

2023-07-28 03:20 UTC, TomattmanYandex approved these changes
Привет, отлично принято.
Касательно твоего комента про покрытие всех/всего проекта документацией, не стоит,
я сторонник идеи, что лучшая документация, это хорошо написанный и структурированный код, и я акцентировал на это внимание при проверке, так что лично мое мнение, комментарии стоит использовать только в крайних случаях, и если очень хочется написать комментарий с объяснением что тут происходит, то это или очень сложная логика, либо код написан не очень

2023-07-28 07:02 UTC, merged